# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KiwiFolk
email: admin@session.nz
description: > # this means to ignore newlines until "baseurl:"
  Folk and Acoustic Music in New Zealand.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kiwifolk.org.nz" # the base hostname & protocol for your site
facebook: https://www.facebook.com/Kiwifolk/
jekyll: https://jekyllrb.com
github: https://github.com/slow-session/kiwifolk.org.nz
mp3_host: "" # leave blank if mp3 files are served from THIS SERVER

# Build settings
markdown: kramdown


